### ISSUE TITLE
This is completely broken

### ISSUE THREAD

**Issue by Blazeolmo** [YTP-Plus/YTPPlusLauncher#2] opened 2021-06-12 10:41 UTC
![Screenshot (10)](https://user-images.githubusercontent.com/85788260/121773325-83f1a600-cb7b-11eb-9475-dbd9b1dbd43c.png)

**Comment by ArdenyUser** [comment] 2021-07-24 18:07
The same issue with me.

**Comment by Danchat5** [comment] 2021-08-31 04:54
Same issue here.

**Comment by MagikGimp** [comment] 2022-03-23 00:29
For convenience (you have to accept an [invite to the Discord channel](https://discord.gg/8ppmspR6Wh) before you can read that FAQ linked by Dan above. Thanks Dan!) here's what you have to do to make it work (I think the original install script has a typo or the procedure lacks certain permissions?) And you did install the prerequisites beforehand, right? [See here if not](https://ytp-plus.github.io/#/articles/installing). Oh and I did everything from a folder in the root of C:\ e.g. C:\YTPPlus to avoid other problems with UAC etc. Anyway, this worked for me:

_The ytp+ launcher gives an 'attempt to concatenate a nil value' error, how do I solve this?_
│ └─ **You must manually clone/install ytp+ cli to the launcher's search path alongside deleting any existing YTPPlusCLI folders.**
│ You may use the following commands to proceed to manually install ytp+ cli: _[In Windows, (assuming you ticked the box to allow Git integration in the right-click Explorer menu during its installation) just right click and Git Bash Here._
```
cd <Search Path>
git clone https://github.com/YTP-Plus/YTPPlusCLI.git
cd YTPPlusCLI
npm install
```
│ On Windows platforms, your search path will be the folder where the *.exe file is located. (i.e. C:\Users\Kiwi\Desktop\YTPPlusLauncher)
│ On other platforms (or if you are using the *.love file), your search path will be in your Application Data directory under ./LOVE/ytpplusstudio_1.
│ These are the search paths that may be used per-platform for *.love files:
│ %APPDATA%\LOVE\ytpplusstudio_1 on Windows
│ ~/.local/share/love/ytpplusstudio_1 on Linux
│ ~/Library/Application Support/LOVE/ytpplusstudio_1 on macOS

Love the interface! Now I just got to figure out how to make poop gold...

**Comment by Blazeolmo** [comment] 2022-04-02 15:51
> For convenience (you have to accept an [invite to the Discord channel](https://discord.gg/8ppmspR6Wh) before you can read that FAQ linked by Dan above. Thanks Dan!) here's what you have to do to make it work (I think the original install script has a typo or the procedure lacks certain permissions?) And you did install the prerequisites beforehand, right? [See here if not](https://ytp-plus.github.io/#/articles/installing). Oh and I did everything from a folder in the root of C:\ e.g. C:\YTPPlus to avoid other problems with UAC etc. Anyway, this worked for me:
> 
> _The ytp+ launcher gives an 'attempt to concatenate a nil value' error, how do I solve this?_ │ └─ **You must manually clone/install ytp+ cli to the launcher's search path alongside deleting any existing YTPPlusCLI folders.** │ You may use the following commands to proceed to manually install ytp+ cli: _[In Windows, (assuming you ticked the box to allow Git integration in the right-click Explorer menu during its installation) just right click and Git Bash Here and proceed from the 2nd step.]_
> 
> ```
> cd <Search Path>
> git clone https://github.com/YTP-Plus/YTPPlusCLI.git
> cd YTPPlusCLI
> npm install
> ```
> 
> │ On Windows platforms, your search path will be the folder where the *.exe file is located. (i.e. C:\Users\Kiwi\Desktop\YTPPlusLauncher) │ On other platforms (or if you are using the *.love file), your search path will be in your Application Data directory under ./LOVE/ytpplusstudio_1. │ These are the search paths that may be used per-platform for *.love files: │ %APPDATA%\LOVE\ytpplusstudio_1 on Windows │ ~/.local/share/love/ytpplusstudio_1 on Linux │ ~/Library/Application Support/LOVE/ytpplusstudio_1 on macOS
> 
> Love the interface! Now I just got to figure out how to make poop gold...

but why all this pain? i'm a simple man, and i dont fucking use command lines because the 80s are kinda over. so why is every single fucking project on github plagued by infinite user unfriendlyness?

**Comment by MagikGimp** [comment] 2022-04-03 12:08
The CLI never went away, mate. It's very little work TBH.
I think the problem is that GitHub requires that its own software (Git) be used exclusively to clone the necessary extra repository, for security reasons presumably. This external repo contains the actual guts that make the videos and cloning cannot be done directly via YTP Plus Launcher (YTP Plus CLI is a separate project, this is just a front-end).
Theoretically you could make YTPs entirely by command line, but I'm getting the feeling you wouldn't be up for that. Just a hunch.

**Comment by KiwifruitDev** [comment] 2023-07-20 08:21
This repository is not supported anymore.

**Closed by KiwifruitDev** 2023-07-20 08:21 UTC
